services:
  - type: web
    name: moemoe
    env: docker
    repo: https://github.com/OKN1212/moemoetest.git
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /health
    dockerfilePath: ./docker/render/Dockerfile   
